DROP DATABASE IF EXISTS curious_rose_journal;
CREATE DATABASE curious_rose_journal;
USE curious_rose_journal;

CREATE TABLE users (
    user_id INT(11) NOT NULL PRIMARY KEY,
    firstName VARCHAR(25),
    lastName VARCHAR(35),
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions(
user_id INT(11) NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
token VARCHAR(100) NOT NULL UNIQUE

);

CREATE TABLE journals(
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    user_id INT(11) REFERENCES users (user_id),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE entries(
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    journal_id INT(11) REFERENCES journals (id),
    contents VARCHAR(3000),
    mood TINYINT(1), 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);