USE heroku_f43acdfbd975755;

CREATE TABLE users (
    user_id INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    firstName VARCHAR(25),
    lastName VARCHAR(35),
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions(
user_id INT(11) NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
token VARCHAR(100) NOT NULL UNIQUE

);

-- CREATE TABLE journals(
--     id INT(11) AUTO_INCREMENT PRIMARY KEY,
--     user_id INT(11) REFERENCES users (user_id),
--     createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

CREATE TABLE entries(
    -- journal_id INT(11) REFERENCES journals (id),
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    user_id INT(11) REFERENCES users (user_id),
    title VARCHAR(100), 
    mood TINYINT(1), 
    q1a1 VARCHAR(500),
    q1a2 VARCHAR(500),
    q1a3 VARCHAR(500), 
    q2 VARCHAR(1000), 
    q3 VARCHAR(1000), 
    q4 VARCHAR(1000), 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);